apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-newsfeed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mssql-claim-newsfeed
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: managed-csi
#   resources:
#     requests:
#       storage: 200Mi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mssql-claim-user
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: managed-csi
#   resources:
#     requests:
#       storage: 200Mi

