apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  SA_PASSWORD: UGE1NXcwcmQh
  twcs: U2VydmVyPW1zc3FsLWNsdXN0ZXJpcC1zcnYsMTQzMztJbml0aWFsIENhdGFsb2c9dHdlZXRzZGI7VXNlciBJRD1zYTtQYXNzd29yZD1QYTU1dzByZCE7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==
